# Development Environment Configuration
environment: development

# Database Configuration
database:
  host: localhost
  port: 5432
  name: airflow
  user: airflow
  password: airflow
  pool_size: 5
  max_overflow: 10

# Airflow Configuration
airflow:
  executor: LocalExecutor
  max_active_runs: 1
  parallelism: 4
  max_active_tasks_per_dag: 2
  load_examples: false
  catchup_by_default: false

# Data Processing Configuration
processing:
  window_size: 20
  batch_size: 1000
  max_processing_time_seconds: 300
  enable_state_persistence: true
  state_file_retention_days: 7

# File Paths
paths:
  data_dir: /opt/airflow/data
  results_dir: /opt/airflow/results
  logs_dir: /opt/airflow/logs
  state_dir: /opt/airflow/results

# Monitoring & Alerting
monitoring:
  enable_metrics: true
  enable_health_checks: true
  alert_on_failure: false
  alert_email: dev@company.com

# Security
security:
  enable_auth: false
  fernet_key: ""
  secret_key: dev-secret-key

# Performance
performance:
  enable_profiling: true
  max_memory_usage_mb: 1024
  task_timeout_seconds: 1800
