# Staging Environment Configuration
environment: staging

# Database Configuration
database:
  host: ${DB_HOST}
  port: ${DB_PORT:-5432}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool_size: 10
  max_overflow: 20
  ssl_mode: require

# Airflow Configuration
airflow:
  executor: LocalExecutor
  max_active_runs: 2
  parallelism: 8
  max_active_tasks_per_dag: 4
  load_examples: false
  catchup_by_default: false

# Data Processing Configuration
processing:
  window_size: 20
  batch_size: 5000
  max_processing_time_seconds: 600
  enable_state_persistence: true
  state_file_retention_days: 30

# File Paths
paths:
  data_dir: /opt/airflow/data
  results_dir: /opt/airflow/results
  logs_dir: /opt/airflow/logs
  state_dir: /opt/airflow/results

# Monitoring & Alerting
monitoring:
  enable_metrics: true
  enable_health_checks: true
  alert_on_failure: true
  alert_email: staging-alerts@company.com
  slack_webhook: ${SLACK_WEBHOOK_URL}

# Security
security:
  enable_auth: true
  fernet_key: ${AIRFLOW_FERNET_KEY}
  secret_key: ${AIRFLOW_SECRET_KEY}

# Performance
performance:
  enable_profiling: false
  max_memory_usage_mb: 2048
  task_timeout_seconds: 3600

# Backup & Recovery
backup:
  enable_backups: true
  backup_schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
